# Generated by Django 3.0.3 on 2020-03-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uan', models.CharField(max_length=20)),
                ('case_id', models.CharField(max_length=20)),
                ('candidate_fname', models.CharField(max_length=50)),
                ('candidate_mname', models.CharField(max_length=50)),
                ('candidate_lname', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('date_of_releiving', models.DateField()),
                ('company_name', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=200)),
                ('status_code', models.BooleanField()),
                ('consent', models.BooleanField()),
                ('request_json', models.CharField(max_length=250)),
            ],
        ),
    ]
