# Generated by Django 3.0.3 on 2020-03-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100, null=True)),
                ('client_name', models.CharField(max_length=200, null=True)),
                ('date_of_joining', models.DateField(null=True)),
                ('date_of_releiving', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(max_length=20)),
                ('name_match', models.BooleanField()),
                ('doj_match', models.BooleanField()),
                ('dor_match', models.BooleanField()),
                ('company_match', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Uan_response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uan', models.CharField(max_length=20)),
                ('check_id', models.CharField(max_length=20)),
                ('candidate_fname', models.CharField(max_length=50)),
                ('candidate_mname', models.CharField(max_length=50, null=True)),
                ('candidate_lname', models.CharField(max_length=50, null=True)),
                ('date_of_joining', models.DateField(null=True)),
                ('date_of_releiving', models.DateField(null=True)),
                ('company_name', models.CharField(max_length=200)),
                ('request_json', models.CharField(max_length=250)),
                ('response_json', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='case_id',
            new_name='check_id',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_mname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='client_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='client_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='consent',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='date_of_releiving',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status_code',
            field=models.BooleanField(default=0),
        ),
    ]
