# Generated by Django 3.0.3 on 2020-03-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapi', '0003_auto_20200302_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='check_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='consent',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='date_of_joining',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='request_json',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status_code',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match_result',
            name='check_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match_result',
            name='company_match',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='match_result',
            name='doj_match',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='match_result',
            name='dor_match',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='match_result',
            name='name_match',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='uan_response',
            name='candidate_fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uan_response',
            name='check_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uan_response',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='uan_response',
            name='request_json',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='uan_response',
            name='response_json',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
