# Generated by Django 3.0.3 on 2020-03-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapi', '0004_auto_20200304_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='consent',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='date_of_joining',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='date_of_releiving',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
