# Generated by Django 3.0.3 on 2020-03-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapi', '0006_auto_20200304_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date_of_releiving',
            field=models.DateField(null=True),
        ),
    ]
